"""
Django settings for arvyo_core project.

Generated by 'django-admin startproject' using Django 5.2.6.
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
SECRET_KEY = 'django-insecure-3mib&i@80nukn4^h6gl(hh%d*q-o))vh7bm%&(da8#g2!f8(yd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

     # --- Apps de Terceiros ---
    'rest_framework',

    # --- Nossos Apps ---
    'financeiro_api', # Nosso app principal
    'corsheaders', # CRUCIAL: Deve estar aqui para CORS
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware', # Deve estar perto do topo
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    
    # 1. MOVIDO PARA CÁ: AUTENTICAÇÃO
    'django.contrib.auth.middleware.AuthenticationMiddleware', 
    'django.contrib.messages.middleware.MessageMiddleware',
    
    # 2. MOVIDO PARA CÁ: CSRF (Deve ser um dos últimos a agir)
    'django.middleware.csrf.CsrfViewMiddleware', 
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'arvyo_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'arvyo_core.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ===============================================
# CONFIGURAÇÕES DE INTEGRAÇÃO FRONT-END (CORS/CSRF/COOKIES)
# ===============================================

# 1. CORS (Permite requisições do Front-end)
CORS_ALLOW_ALL_ORIGINS = False 

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

# 2. Permite o envio/recebimento de cookies de sessão (crucial para o login)
CORS_ALLOW_CREDENTIALS = True 

# 3. CSRF (Permite que o Front-end faça POSTs)
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

# 4. CRUCIAL: Ajusta a política de cookies para aceitar a comunicação entre portas diferentes.
# O 'None' é necessário para desativar a proteção 'SameSite' no desenvolvimento.
SESSION_COOKIE_SAMESITE = None
CSRF_COOKIE_SAMESITE = None

# 5. AJUSTE CRÍTICO E CONDICIONAL: A política Secure (HTTPS)
# Se estiver em modo DEBUG (desenvolvimento/HTTP), desativamos a segurança do cookie
# para que o navegador não os bloqueie.
if DEBUG:
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False
else:
    # EM PRODUÇÃO (DEBUG=False), a segurança do cookie é CRÍTICA.
    # Assumimos que o servidor estará em HTTPS e reativamos a proteção.
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True 

# 6. NOVIDADE FINAL: Permite que o Django CORS aceite todos os headers comuns,
# CRUCIALMENTE incluindo o X-CSRFToken.
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken', # CRÍTICO! Garante que o Django aceite o token CSRF no header.
    'x-requested-with',
]

# NOVIDADE CRÍTICA: Diz ao Django para armazenar o token CSRF na sessão (e não no cookie).
# Isso geralmente resolve conflitos de cookies em configurações cross-origin (React/Django).
CSRF_USE_SESSIONS = True 

# NOVIDADE PARA CORRIGIR 403: Garante que os cookies funcionem corretamente no localhost.
SESSION_COOKIE_DOMAIN = None
