# Generated by Django 5.2.6 on 2025-09-29 21:30

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('limite', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fatura_pendente', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('dia_vencimento', models.IntegerField()),
                ('dia_fechamento', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('saldo_atual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Floresta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos_acumulados', models.IntegerField(default=0)),
                ('arvores_virtuais', models.IntegerField(default=0)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa'), ('TRANSFERENCIA', 'Transferência')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data', models.DateField()),
                ('categoria', models.CharField(blank=True, choices=[('ESSENCIAL', 'Essencial (Necessidades - 50%)'), ('ESTILO_DE_VIDA', 'Estilo de Vida (Desejos - 30%)'), ('FUTURO', 'Futuro (Poupança/Investimento - 20%)')], max_length=20, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, help_text='Tags opcionais (Ex: #alimentação, #viagem)', max_length=255)),
                ('cartao', models.ForeignKey(blank=True, help_text='Cartão utilizado na despesa.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro_api.cartao')),
                ('conta', models.ForeignKey(blank=True, help_text='Conta de origem/destino do valor.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro_api.conta')),
                ('conta_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_recebidas', to='financeiro_api.conta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
